version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rentcar-postgres
    environment:
      POSTGRES_DB: rentcar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rentcar-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: rentcar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rentcar-network
    restart: unless-stopped

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rentcar-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rentcar.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rentcar-network
    depends_on:
      - postgres
    restart: unless-stopped

  # Application (uncomment when ready to run)
  # app:
  #   build: .
  #   container_name: rentcar-backend
  #   environment:
  #     NODE_ENV: development
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: password
  #     DB_NAME: rentcar_db
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   networks:
  #     - rentcar-network
  #   depends_on:
  #     - postgres
  #     - redis
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  rentcar-network:
    driver: bridge 